### ISSUE TITLE
dotnet build command fails

### ISSUE THREAD

**Issue by IgorKaplya** [semiodesk/trinity-rdf#13]
Good day, when we try to build a web application for Linux from the Azure pipeline:

We get the following error:
##[error]C:\Users\VssAdministrator\.nuget\packages\semiodesk.trinity\1.0.3.50\build\Semiodesk.Trinity.targets(12,5): Error : ICSharpCode.Decompiler.Metadata.AssemblyResolutionException: Failed to resolve assembly: 'Semiodesk.Trinity, Version=1.0.3.50, Culture=neutral, PublicKeyToken=null'
   at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.ResolveInternal(IAssemblyReference name)
   at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.FindAssemblyFile(IAssemblyReference name)
   at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.Resolve(AssemblyNameReference name)
   at Semiodesk.Trinity.CilGenerator.ILGenerator.ProcessFile(String sourceFile, String targetFile)

At the same time, the project is being built and published to Linux from VS just fine. 
![image](https://user-images.githubusercontent.com/59043912/140101700-27932fd5-dc27-43cc-835c-6250f34de284.png)

It is possible to reproduce the mentioned behavior:
1. Checkout trinity examples repo
2. Run: "C:\Program Files\dotnet\dotnet.exe" build "Examples.sln" -c Release -r linux-x64 -p:ImportByWildcardBeforeSolution=false

**Comment by IgorKaplya** [comment]
One important thing here is that the model and the reference to a Trinity NuGet are localized in a separate class-type library project.

Eventually, the problem is caused by a missing Semiodesk.Trinity.dll in the target  `Linux-x64` folder, where the decompiler tries to do the task: `ILGenerator.ProcessFile(String sourceFile, String targetFile)`, as soon as I copied DLL to the specified folder build succeeded.

Found a workaround for this issue:

```xml
  <PropertyGroup>
    <!--Add this line-->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
```

That will force the compilation subsystem to copy NuGet assemblies to the output during the build. Of course, that will consume extra disk space, but your build script will be nice and elegant :)

**Comment by faubulous** [comment]
Hi Igor!

Thank you for information and for sharing the workaround. Do I understand correctly that the PropertyGroup code must be included in the .csproj file of the project referencing the NuGet package?

I wonder how we best resolve the issue.. does the problem only occur with Linux x64 targets?

**Comment by IgorKaplya** [comment]
Hi @faubulous, I've tried linux-arm - same problem. You're right, the one that references trinity is enough(I've updated the post). 

Problem is caused by ILGenerator.ProcessFile() code that`s all I can tell :)   Maybe some information from this topic will be helpful: https://github.com/icsharpcode/ILSpy/issues/2021

**Comment by faubulous** [comment]
OK, thanks. We'll need to investigate this.
